repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.5
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter  
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        types: [python]
        pass_filenames: false

# Notes:
# 1. `uv-lock` hook automatically updates the lockfile to ensure it matches specs in pyproject.toml
# 2. `--exit-non-zero-on-fix` flag blocks commits when ruff makes automatic fixes, must review first
# 3. `pass_filenames`: false` makes pytest run all tests rather than only testing modified files