[project]
name = "youtube-to-xml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Michelle", email = "" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
youtube-to-xml = "youtube_to_xml:main"

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"
